image:
  repository: ghcr.io/jneuff/idempotent-secrets/images
  name: idempotent-secrets
  tag: sha-0f7b63cddae423ba83ccc21b3ab6080ac0a50c3b

secrets:
#   - name: secret-1
#     type: RsaKeypair
#   - name: secret-2
#     type: RandomString

fullnameOverride: ""
