image:
  repository: ghcr.io/jneuff/idempotent-secrets/images
  name: idempotent-secrets
  tag: sha-91ae6ce3bdc5ae4bf2062c61eb207c78190162ec

secrets:
#   - name: secret-1
#     type: RsaKeypair
#   - name: secret-2
#     type: RandomString

fullnameOverride: ""
