image:
  repository: ghcr.io/jneuff/idempotent-secrets/images
  name: idempotent-secrets
  tag: sha-a680d7edce8ce44e6dda0bb11a9fe04ede3c7699

secrets:
#   - name: secret-1
#     type: RsaKeypair
#   - name: secret-2
#     type: RandomString

fullnameOverride: ""
