image:
  repository: ghcr.io/jneuff/idempotent-secrets/images
  name: idempotent-secrets
  tag: sha-a8c0f32dc50d88ace3ed04f501f5529112a65078

secrets:
#   - name: secret-1
#     type: RsaKeypair
#   - name: secret-2
#     type: RandomString

fullnameOverride: ""
